development:
  adapter: postgresql
  database: im_cropper_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: im_cropper_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: im_cropper_production
  pool: 5
  timeout: 5000
